### ISSUE TITLE
Aimbot is Dogshit

### ISSUE THREAD

**Issue by RandomV1234** [secretlay3r/Dividence-for-Spectre-Divide#1]
if you throw your duple the aimbot gets right on to it and no matter how undetected this is, you will be get banned cause your team will see how weird you walking with the aim like left right left right left right. and the recoil reduction with the aimbot enabled aims way to low. and if you throw the duple the triggerbot shoots automaticly. i tried id with all colors but all are bad.

**Comment by popabobr** [comment]
you are like this aimbot
dog this aim is one week old wtf
